version: "3.9"

services:
  fastapi:
    build: .
    command: ["bash", "-c", "python3 run_fast_api.py"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    env_file:
      - .env
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5050:80
    depends_on:
      - postgresql
volumes:
  db-data:
