version: "3.9"

services:
  fastapi:
    image: python-3.10-fastapi
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    command: ["bash", "-c", "python3 run_fast_api.py"]
    volumes:
      - .:/app
    networks:
      - school_plataform_network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5050:80
    depends_on:
      - postgresql
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - school_plataform_network
networks:
  school_plataform_network:
    driver: bridge

volumes:
  db-data: