version: "3.9"
services:
  fastapi:
    image: python-3.10-fastapi
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    command: ["bash", "-c", "poetry run uvicorn src.infra.fast_api.server:app --host 0.0.0.0 --port 8000"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
